# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bucketcreated:
  # runs-on means a os where we do our work
    runs-on : ubuntu-latest 
    steps:
    # uses is workspace 
      - uses: actions/checkout@v3 
      - name: Terraform hashicorp setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: "ap-south-1"
      - name: terraform init
        run: |
          cd s3
          terraform init
      - name: terraform plan
        run: |
          cd s3
          terraform plan
        
      - name: terraform apply
        run: |
          cd s3
          terraform apply -auto-approve

    